export default {
    async fetch(request, env) {

        // Only allow POST
        if (request.method !== "POST") {
            return new Response("Use POST", { status: 405 });
        }

        // Parse JSON from the request body
        let data;
        try {
            data = await request.json();
        } catch (err) {
            return new Response("Invalid JSON", { status: 400 });
        }

        const prompt = data.text || "default prompt";

        const inputs = {
            prompt: prompt,
        };

        // Run the model
        const response = await env.AI.run(
            "@cf/black-forest-labs/flux-1-schnell",
            inputs
        );

        // Return image generated by Worker AI
        return new Response(response, {
            headers: {
                "content-type": "image/png",
            },
        });
    },
};
